name: Publish

on:
  push:
    branches:
      - main
      - next

  workflow_dispatch:
    branches:
      - main
      - next

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Set @johnlindquist/kit@tag to next or main
        id: set_kit_version
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "kit_tag=latest" >> $GITHUB_OUTPUT
          else
            echo "kit_tag=next" >> $GITHUB_OUTPUT
          fi

      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic # Need an `id` for output variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify that Semantic Release updated package.json
        run: |
          cat package.json
          echo ${{ steps.semantic.outputs.new_release_version }} > semantic-version.txt
          echo "SEMANTIC_VERSION=$(cat semantic-version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: johnlindquist/kit-action@main
        with:
          script: create-release ${{ env.SEMANTIC_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Write the Release id to release-id.txt
        run: |
          echo ${{ steps.create_release.outputs.result }} > release-id.txt

      - name: Upload Semantic Version Artifact
        uses: actions/upload-artifact@v3
        with:
          name: semantic-version
          path: semantic-version.txt

      - name: Upload Release id Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-id
          path: release-id.txt

  publish:
    needs: semantic
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest, ubuntu-latest]
        arch: [x64, arm64]
        node: [20.9.0]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Download Semantic Version Artifact
        uses: actions/download-artifact@v3
        with:
          name: semantic-version

      - name: Download Release id Artifact
        uses: actions/download-artifact@v3
        with:
          name: release-id

      - name: Nix - Set Semantic Version
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          echo "Semantic Version: $(cat semantic-version.txt)"
          # Set the semantic version as an environment variable
          echo "SEMANTIC_VERSION=$(cat semantic-version.txt)" >> $GITHUB_ENV

          echo "Release id: $(cat release-id.txt)"
          # Set the release id as an environment variable
          echo "RELEASE_ID=$(cat release-id.txt)" >> $GITHUB_ENV

      - name: Windows - Set Semantic Version
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "Semantic Version: $(cat semantic-version.txt)"
          # Set the semantic version as an environment variable
          echo "SEMANTIC_VERSION=$(cat semantic-version.txt)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          echo "Release id: $(cat release-id.txt)"
          # Set the release id as an environment variable
          echo "RELEASE_ID=$(cat release-id.txt)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Write the Semantic Version to package.json version property
        uses: johnlindquist/kit-action@main
        with:
          script: update-package-version ${{ env.SEMANTIC_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Nix - Write the current branch to a releaseChannel env var
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          echo "RELEASE_CHANNEL=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - name: Windows - Write the current branch to a releaseChannel env var
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "RELEASE_CHANNEL=$(git rev-parse --abbrev-ref HEAD)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Download kenv
        uses: johnlindquist/kit-action@main
        with:
          script: download-kenv ${{ env.RELEASE_CHANNEL }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Assets
        uses: johnlindquist/kit-action@main
        with:
          script: create-assets ${{ env.SEMANTIC_VERSION }} ${{ matrix.os }} ${{ matrix.arch }} ${{ env.RELEASE_ID }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      # - name: Ubuntu Electron Issue
      #   if: matrix.os == 'ubuntu-latest'
      #   run: echo "There is an issue with electron >=26 with something in the app causing a crash. It might be with the powerMonitor, but it's still not clear. This will have to be resolved before we can upgrade electron and move to ESM-only."
      #   env:
      #     KIT_TAG: ${{ needs.semantic.outputs.kit_tag }}
      # # - name: npm i @johnlindquist/kit
      # #   if: matrix.os == 'ubuntu-latest'
      # #   run: |
      # #     # npm i
      # #     npm i electron@25.9.3
      # #     npm i "@johnlindquist/kit@${{ env.KIT_TAG }}"

      - name: Publish windows x64
        if: matrix.os == 'windows-latest' && matrix.arch == 'x64'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: |
            npm un node-mac-permissions @johnlindquist/mac-clipboard-listener @johnlindquist/mac-frontmost @johnlindquist/mac-panel-window
            npm i @johnlindquist/kit@${{ needs.semantic.outputs.kit_tag }}
            npm i
            npx kit remove-mac
            Push-Location node_modules\uiohook-napi\prebuilds; Get-ChildItem | Where-Object { $_.Name -notmatch '^win' } | Remove-Item -Recurse -Force; Pop-Location
            if (Test-Path node_modules\@nut-tree\libnut-darwin) { Remove-Item node_modules\@nut-tree\libnut-darwin -Recurse -Force }
            if (Test-Path node_modules\@nut-tree\libnut-linux) { Remove-Item node_modules\@nut-tree\libnut-linux -Recurse -Force }
            cat ./package.json
            echo "--- Done removing mac deps ---\n\n"
            npm run vite-prebuild
            npx kit ./build.ts mac x64 always

      - name: Publish windows arm64
        if: matrix.os == 'windows-latest' && matrix.arch == 'arm64'
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: |
            npm un node-mac-permissions @nut-tree/nut-js uiohook-napi @johnlindquist/mac-clipboard-listener @johnlindquist/mac-frontmost @johnlindquist/mac-panel-window
            npm i @johnlindquist/kit@${{ needs.semantic.outputs.kit_tag }}
            npm i
            npx kit remove-tick
            npx kit remove-mac
            npx kit remove-nut
            echo "--- Done removing mac deps ---\n\n"
            npm run vite-prebuild
            npx kit ./build.ts win arm64 always
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish linux x64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: |
            npm un node-mac-permissions @johnlindquist/mac-clipboard-listener @johnlindquist/mac-frontmost @johnlindquist/mac-panel-window @johnlindquist/node-window-manager node-pty
            npm i @johnlindquist/kit@${{ needs.semantic.outputs.kit_tag }}
            npm i
            npx kit remove-mac
            npx kit remove-node-window-manager
            # npx kit patch-node-pty
            npm i @homebridge/node-pty-prebuilt-multiarch
            cat ./package.json
            echo "--- Done removing mac deps ---\n\n"
            npm run vite-prebuild
            npx kit ./build.ts linux x64 always

      - name: Publish linux arm64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: |
            npm un node-mac-permissions @nut-tree/nut-js uiohook-napi @johnlindquist/mac-clipboard-listener @johnlindquist/mac-frontmost @johnlindquist/mac-panel-window @johnlindquist/node-window-manager node-pty
            npm i @johnlindquist/kit@${{ needs.semantic.outputs.kit_tag }}
            npm i
            npx kit remove-tick
            npx kit remove-mac
            npx kit remove-nut
            npx kit remove-node-window-manager
            # npx kit patch-node-pty
            npm i @homebridge/node-pty-prebuilt-multiarch
            cat ./package.json
            echo "--- Done removing mac deps ---\n\n"
            npm run vite-prebuild
            npx kit ./build.ts linux arm64 always

      - name: Publish mac x64
        if: matrix.os == 'macos-13' && matrix.arch == 'x64'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: |
            npm i @johnlindquist/kit@${{ needs.semantic.outputs.kit_tag }}
            npm i
            npm run vite-prebuild
            npx kit ./build.ts mac x64 always

      - name: Publish mac arm64
        if: matrix.os == 'macos-13' && matrix.arch == 'arm64'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: |
            npm i @johnlindquist/kit@${{ needs.semantic.outputs.kit_tag }}
            npm i
            npm run vite-prebuild
            npx kit ./build.ts mac arm64 always

      - name: Merge latest-mac.yml and latest-mac-arm64.yml
        if: matrix.os == 'macos-13'
        uses: johnlindquist/kit-action@main
        with:
          script: merge-mac-latest-yml johnlindquist kitapp ${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
